periodics:
  - name: update-maintainers
    # interval: 15m
    cron: "0 9 * * 5" # Run at 09:00 only on Fridays
    decorate: true
    extra_refs:
    # Check out the repo containing the maintainers file
    - org: falcosecurity
      repo: .github
      base_ref: master
    spec:
      containers:
      # See images/update-maintainers
      - image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/update-maintainers
        imagePullPolicy: Always
        command:
        - sleep
        # - entrypoint.sh
        args:
        - "900"
        # - /etc/github-token/oauth
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
          readOnly: true
        - name: gpg-signing-key
          mountPath: /root/gpg-signing-key/
          readOnly: true
    volumes:
    - name: github
      secret:
        # Secret containing a GitHub user access token with `repo` scope for creating PRs.
        secretName: oauth-token
    - name: gpg-signing-key
      secret:
        secretName: poiana-gpg-signing-key
        defaultMode: 0400