periodics:
  - name: update-maintainers
    cron: "0 9 * * 5" # Run at 09:00 only on Fridays # Local testing: substitute with => interval: 15m
    decorate: true
    extra_refs:
    # Check out the repo containing the maintainers file
    # This will be the working directory
    - org: falcosecurity
      repo: .github
      base_ref: master
      workdir: true
    spec:
      containers:
      # See images/update-maintainers
      - image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/update-maintainers # Local testing: substitute with => image: localhost:5000/update-maintainers
        imagePullPolicy: Always
        command:
        - /entrypoint.sh # Local testing: sleep
        args:
        - /etc/github-token/oauth # Local testing: substitute with => - "900"
        env:
        - name: GH_PROXY
          value: https://api.github.com # fixme > Can't reach http://ghproxy at the moment
        # Local testing: comment
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
          readOnly: true
        - name: gpg-signing-key
          mountPath: /root/gpg-signing-key/
          readOnly: true
      # Local testing: comment
      volumes:
      - name: github
        secret:
          # Secret containing a GitHub user access token with `repo` scope for creating PRs.
          secretName: oauth-token
      - name: gpg-signing-key
        secret:
          secretName: poiana-gpg-signing-key
          defaultMode: 0400
      nodeSelector:
        Archtype: "x86"
