# PROW_INSTANCE_SPECIFIC
# Slack endpoint, or even different methods of alerting
# Please replace '{{ api_url }}' below with the URL of slack incoming hook
# before `kubectl apply -f`
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prow
  namespace: prow-monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 10m
      repeat_interval: 4h
      receiver: 'slack-warnings'
      routes:
      - receiver: 'cluster-api-aws-alerts'
        group_interval: 5m
        repeat_interval: 2h
        match:
          boskos_type: aws-account
      - receiver: 'slack-alerts'
        group_interval: 5m
        repeat_interval: 2h
        match_re:
          severity: 'critical|high'


    receivers:
    - name: 'slack-warnings'
      slack_configs:
      - channel: '#prow-alerts'
        api_url: '{{ api_url }}'
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        text: '@test-infra-oncall {{ template "custom_slack_text" . }}'
        link_names: true
    - name: 'slack-alerts'
      slack_configs:
      - channel: '#testing-ops'
        api_url: '{{ api_url }}'
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        text: '@test-infra-oncall {{ template "custom_slack_text" . }}'
        link_names: true
    - name: 'cluster-api-aws-alerts'
      slack_configs:
      - channel: '#cluster-api-aws-alerts'
        api_url: '{{ api_url }}'
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        text: '@aws-account-users {{ template "custom_slack_text" . }}'
        link_names: true

    templates:
    - '*.tmpl'
  msg.tmpl: |
    {{ define "custom_slack_text" }}{{ .CommonAnnotations.message }}{{ end }}
type: Opaque
