# PROW_INSTANCE_SPECIFIC
# Slack endpoint, or even different methods of alerting
# Please replace '{{ api_url }}' below with the URL of slack incoming hook
# before `kubectl apply -f`
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prow
  namespace: prow-monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 10m
      repeat_interval: 4h
      receiver: ""
      routes: []
    receivers: []
    templates:
    - '*.tmpl'
  msg.tmpl: |
    {{ define "custom_slack_text" }}{{ .CommonAnnotations.message }}{{ end }}
type: Opaque
