periodics:
  - name: update-syscalls
    cron: '0 6 1 * *'  # every 1st day of month, at 6am
    decorate: true
    extra_refs:
    - org: falcosecurity
      repo: libs
      base_ref: master
      workdir: true
    spec:
      containers:
      # See images/update-syscalls
      - image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/update-syscalls
        imagePullPolicy: Always
        command:
        - /entrypoint.sh
        args:
        - /etc/github-token/oauth
        env:
        - name: GH_PROXY
          value: https://api.github.com # fixme > Can't reach http://ghproxy at the moment
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
          readOnly: true
        - name: gpg-signing-key
          mountPath: /root/gpg-signing-key/
          readOnly: true
      volumes:
      - name: github
        secret:
          # Secret containing a GitHub user access token with `repo` scope for creating PRs.
          secretName: oauth-token
      - name: gpg-signing-key
        secret:
          secretName: poiana-gpg-signing-key
          defaultMode: 0400
      nodeSelector:
        Archtype: "x86"
