#!/usr/bin/env bash
# set -xe

DRIVER_NAME="falco"
PROBE_NAME="falco"

CURRENT_DIR="$(pwd)"

while getopts ":a:k:d:v:h:" arg; do
  case $arg in
    a)
      TARGET_ARCH=${OPTARG}
      ;;
    k)
      TARGET_KERNEL=${OPTARG}
      ;;
    d)
      TARGET_DISTRO=${OPTARG}
      ;;
    v)
      TARGET_VERSION=${OPTARG}
      ;;
    h)
      TARGET_HEADERS=${OPTARG}
      ;;
  esac
done


if [ -z ${TARGET_ARCH} ]; then
    echo "TARGET_ARCH can't be empty"
    exit 1
fi
if [ -z ${TARGET_DISTRO} ]; then
    echo "TARGET_DISTRO can't be empty"
    exit 1
fi
if [ -z ${TARGET_KERNEL} ]; then
    echo "TARGET_KERNEL can't be empty"
    exit 1
fi
if [ -z ${TARGET_VERSION} ]; then
    echo "TARGET_VERSION can't be empty"
    exit 1
fi

compute_kernelversion() {
    TARGET_KERNEL_VERSION=$(echo "${TARGET_KERNEL##*_}")
}

compute_kernelrelease() {
    TARGET_KERNEL_RELEASE="${TARGET_KERNEL%_${TARGET_KERNEL_VERSION}}"
}

arch_to_driverkit_arch() {
	case "$1" in
		"x86_64")
			echo -n "amd64"
			;;
		"aarch64")
			echo -n "arm64"
			;;
		*)
			echo "unknown architecture"
			exit 1
			;;
	esac
}

# If driver version is a semver, we are in the newest case
# thus we must support %arch/ subfolder for configs.
# Else, we are in the old case, and we only support x86_64 configs
# in the TARGET_VERSION folder.
# TODO: rm this once old format support is dropped, and always use ${TARGET_VERSION}/${TARGET_ARCH}
function path_from_version() {
  SEMVER_REGEX="^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(\\-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$"
  if [[ $TARGET_VERSION =~ $SEMVER_REGEX ]]; then
    # valid semver
    echo -n "${TARGET_VERSION}/${TARGET_ARCH}"
  elif [[ $TARGET_ARCH == "aarch64" ]]; then
    # not valid (old versions) -> skip arm64
    echo "Skipping arm64 configs for old tree."
    exit 1
  else
    # not valid (old versions)
    echo -n "${TARGET_VERSION}"
  fi
}

generate_yamls() {
    # TODO: remove once we only support new tree. It is not an error, as we are skipping
    # arm64 configs for old tree.
    SUBPATH=$(path_from_version) || exit 0
    # This is an error: wrong arch passed to make generate
    DKARCH=$(arch_to_driverkit_arch ${TARGET_ARCH}) || exit 1
    FOLDER="${CURRENT_DIR}/../driverkit/config/${SUBPATH}"
    mkdir -p ${FOLDER}
    FILE="${FOLDER}/${TARGET_DISTRO}_${TARGET_KERNEL}.yaml"
    echo "---"
    echo "${FILE}"
    echo "---"
    echo "kernelversion: ${TARGET_KERNEL_VERSION}"
    echo "kernelrelease: ${TARGET_KERNEL_RELEASE}"
    echo "target: ${TARGET_DISTRO}"
    echo "architecture: ${DKARCH}"
    echo "output:"
    echo "  module: output/${SUBPATH}/${DRIVER_NAME}_${TARGET_DISTRO}_${TARGET_KERNEL}.ko"
    echo "  probe: output/${SUBPATH}/${PROBE_NAME}_${TARGET_DISTRO}_${TARGET_KERNEL}.o"
    if [[ -n "${TARGET_HEADERS}" ]]; then
        echo "kernelurls: ${TARGET_HEADERS}"
    fi
    
    echo "kernelversion: ${TARGET_KERNEL_VERSION}" > ${FILE}
    echo "kernelrelease: ${TARGET_KERNEL_RELEASE}" >> ${FILE}
    echo "target: ${TARGET_DISTRO}" >> ${FILE}
    echo "architecture: ${DKARCH}" >> ${FILE}
    echo "output:" >> ${FILE}
    echo "  module: output/${SUBPATH}/${DRIVER_NAME}_${TARGET_DISTRO}_${TARGET_KERNEL}.ko" >> ${FILE}
    echo "  probe: output/${SUBPATH}/${PROBE_NAME}_${TARGET_DISTRO}_${TARGET_KERNEL}.o" >> ${FILE}
    if [[ -n "${TARGET_HEADERS}" ]]; then
        echo "kernelurls: ${TARGET_HEADERS}" >> ${FILE}
    fi   
}

compute_kernelversion
compute_kernelrelease
generate_yamls
