---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "check-prow-config"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-pods
  name: "check-prow-config"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "check-prow-config"
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes