config_updater:
  maps:
    config/prow/aws/config.yaml:
      name: config
      key: config.yaml
    config/prow/aws/plugins.yaml:
      name: plugins
      key: plugins.yaml
    config/jobs/aws/**/*.yaml:
      name: job-config
      gzip: true
triggers:
  - repos:
      - falcosecurity
    join_org_url: https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md
    only_org_members: true
plugins:
  falcosecurity/test-infra:
    plugins:
      - config-updater
      - trigger
