postsubmits:
  falcosecurity/event-generator:
    - name: sync-charts-event-generator
      decorate: true
      max_concurrency: 1
      job_queue_name: automation
      decoration_config:
        timeout: 1h
      branches:
        - ^main$
      run_if_changed: "^chart/event-generator/"
      extra_refs:
        - org: falcosecurity
          repo: charts
          base_ref: master
          workdir: true
      spec:
        serviceAccountName: automation
        automountServiceAccountToken: false
        enableServiceLinks: false
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          fsGroup: 65532
          seccompProfile:
            type: RuntimeDefault
        containers:
          - name: automation
            image: ghcr.io/falcosecurity/test-infra/sync-charts@sha256:83141c27e385964bbddfd13cb6b4e9325c79ec20a3d580ef8be6b997a7d45d73
            command:
              - /entrypoint.sh
            args:
              - /etc/github-token/oauth
            env:
              - name: GH_PROXY
                value: https://api.github.com
              - name: HOME
                value: /home/nonroot
              - name: BOT_GPG_KEY_PATH
                value: /etc/gpg/poiana.asc
              - name: GH_REPO
                value: "charts"
              - name: GH_REPO_BRANCH
                value: "master"
              - name: SOURCE_REPO_PATH
                value: "/home/prow/go/src/github.com/falcosecurity/event-generator"
              - name: SOURCE_CHART_PATH
                value: "chart/event-generator"
              - name: TARGET_CHART_PATH
                value: "charts/event-generator"
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
                ephemeral-storage: 2Gi
              limits:
                cpu: "2"
                memory: 4Gi
                ephemeral-storage: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
            volumeMounts:
              - name: github
                mountPath: /etc/github-token
                readOnly: true
              - name: gpg-signing-key
                mountPath: /etc/gpg
                readOnly: true
              - name: home
                mountPath: /home/nonroot
        volumes:
          - name: github
            secret:
              secretName: oauth-token
              defaultMode: 0440
              items:
                - key: oauth
                  path: oauth
          - name: gpg-signing-key
            secret:
              secretName: poiana-gpg-signing-key
              defaultMode: 0440
              items:
                - key: poiana.asc
                  path: poiana.asc
          - name: home
            emptyDir:
              sizeLimit: 4Gi
        nodeSelector:
          Application: automation
          Archtype: x86
          kubernetes.io/arch: amd64
        tolerations:
          - key: dedicated.falco.org/automation
            operator: Equal
            value: "true"
            effect: NoSchedule
  falcosecurity/falco:
    - name: sync-charts-falco
      decorate: true
      max_concurrency: 1
      job_queue_name: automation
      decoration_config:
        timeout: 1h
      branches:
        - ^release/.*$
      run_if_changed: "^chart/falco/"
      extra_refs:
        - org: falcosecurity
          repo: charts
          base_ref: master
          workdir: true
      spec:
        serviceAccountName: automation
        automountServiceAccountToken: false
        enableServiceLinks: false
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          fsGroup: 65532
          seccompProfile:
            type: RuntimeDefault
        containers:
          - name: automation
            image: ghcr.io/falcosecurity/test-infra/sync-charts@sha256:83141c27e385964bbddfd13cb6b4e9325c79ec20a3d580ef8be6b997a7d45d73
            command:
              - /entrypoint.sh
            args:
              - /etc/github-token/oauth
            env:
              - name: GH_PROXY
                value: https://api.github.com
              - name: HOME
                value: /home/nonroot
              - name: BOT_GPG_KEY_PATH
                value: /etc/gpg/poiana.asc
              - name: GH_REPO
                value: "charts"
              - name: GH_REPO_BRANCH
                value: "master"
              - name: SOURCE_REPO_PATH
                value: "/home/prow/go/src/github.com/falcosecurity/falco"
              - name: SOURCE_CHART_PATH
                value: "chart/falco"
              - name: TARGET_CHART_PATH
                value: "charts/falco"
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
                ephemeral-storage: 2Gi
              limits:
                cpu: "2"
                memory: 4Gi
                ephemeral-storage: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
            volumeMounts:
              - name: github
                mountPath: /etc/github-token
                readOnly: true
              - name: gpg-signing-key
                mountPath: /etc/gpg
                readOnly: true
              - name: home
                mountPath: /home/nonroot
        volumes:
          - name: github
            secret:
              secretName: oauth-token
              defaultMode: 0440
              items:
                - key: oauth
                  path: oauth
          - name: gpg-signing-key
            secret:
              secretName: poiana-gpg-signing-key
              defaultMode: 0440
              items:
                - key: poiana.asc
                  path: poiana.asc
          - name: home
            emptyDir:
              sizeLimit: 4Gi
        nodeSelector:
          Application: automation
          Archtype: x86
          kubernetes.io/arch: amd64
        tolerations:
          - key: dedicated.falco.org/automation
            operator: Equal
            value: "true"
            effect: NoSchedule
  falcosecurity/k8s-metacollector:
    - name: sync-charts-k8s-metacollector
      decorate: true
      max_concurrency: 1
      job_queue_name: automation
      decoration_config:
        timeout: 1h
      branches:
        - ^main$
      run_if_changed: "^chart/k8s-metacollector/"
      extra_refs:
        - org: falcosecurity
          repo: charts
          base_ref: master
          workdir: true
      spec:
        serviceAccountName: automation
        automountServiceAccountToken: false
        enableServiceLinks: false
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          fsGroup: 65532
          seccompProfile:
            type: RuntimeDefault
        containers:
          - name: automation
            image: ghcr.io/falcosecurity/test-infra/sync-charts@sha256:83141c27e385964bbddfd13cb6b4e9325c79ec20a3d580ef8be6b997a7d45d73
            command:
              - /entrypoint.sh
            args:
              - /etc/github-token/oauth
            env:
              - name: GH_PROXY
                value: https://api.github.com
              - name: HOME
                value: /home/nonroot
              - name: BOT_GPG_KEY_PATH
                value: /etc/gpg/poiana.asc
              - name: GH_REPO
                value: "charts"
              - name: GH_REPO_BRANCH
                value: "master"
              - name: SOURCE_REPO_PATH
                value: "/home/prow/go/src/github.com/falcosecurity/k8s-metacollector"
              - name: SOURCE_CHART_PATH
                value: "chart/k8s-metacollector"
              - name: TARGET_CHART_PATH
                value: "charts/k8s-metacollector"
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
                ephemeral-storage: 2Gi
              limits:
                cpu: "2"
                memory: 4Gi
                ephemeral-storage: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
            volumeMounts:
              - name: github
                mountPath: /etc/github-token
                readOnly: true
              - name: gpg-signing-key
                mountPath: /etc/gpg
                readOnly: true
              - name: home
                mountPath: /home/nonroot
        volumes:
          - name: github
            secret:
              secretName: oauth-token
              defaultMode: 0440
              items:
                - key: oauth
                  path: oauth
          - name: gpg-signing-key
            secret:
              secretName: poiana-gpg-signing-key
              defaultMode: 0440
              items:
                - key: poiana.asc
                  path: poiana.asc
          - name: home
            emptyDir:
              sizeLimit: 4Gi
        nodeSelector:
          Application: automation
          Archtype: x86
          kubernetes.io/arch: amd64
        tolerations:
          - key: dedicated.falco.org/automation
            operator: Equal
            value: "true"
            effect: NoSchedule
  falcosecurity/falco-operator:
    - name: sync-charts-falco-operator
      decorate: true
      max_concurrency: 1
      job_queue_name: automation
      decoration_config:
        timeout: 1h
      branches:
        - ^main$
      run_if_changed: "^chart/falco-operator/"
      extra_refs:
        - org: falcosecurity
          repo: charts
          base_ref: master
          workdir: true
      spec:
        serviceAccountName: automation
        automountServiceAccountToken: false
        enableServiceLinks: false
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          fsGroup: 65532
          seccompProfile:
            type: RuntimeDefault
        containers:
          - name: automation
            image: ghcr.io/falcosecurity/test-infra/sync-charts@sha256:83141c27e385964bbddfd13cb6b4e9325c79ec20a3d580ef8be6b997a7d45d73
            command:
              - /entrypoint.sh
            args:
              - /etc/github-token/oauth
            env:
              - name: GH_PROXY
                value: https://api.github.com
              - name: HOME
                value: /home/nonroot
              - name: BOT_GPG_KEY_PATH
                value: /etc/gpg/poiana.asc
              - name: GH_REPO
                value: "charts"
              - name: GH_REPO_BRANCH
                value: "master"
              - name: SOURCE_REPO_PATH
                value: "/home/prow/go/src/github.com/falcosecurity/falco-operator"
              - name: SOURCE_CHART_PATH
                value: "chart/falco-operator"
              - name: TARGET_CHART_PATH
                value: "charts/falco-operator"
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
                ephemeral-storage: 2Gi
              limits:
                cpu: "2"
                memory: 4Gi
                ephemeral-storage: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
            volumeMounts:
              - name: github
                mountPath: /etc/github-token
                readOnly: true
              - name: gpg-signing-key
                mountPath: /etc/gpg
                readOnly: true
              - name: home
                mountPath: /home/nonroot
        volumes:
          - name: github
            secret:
              secretName: oauth-token
              defaultMode: 0440
              items:
                - key: oauth
                  path: oauth
          - name: gpg-signing-key
            secret:
              secretName: poiana-gpg-signing-key
              defaultMode: 0440
              items:
                - key: poiana.asc
                  path: poiana.asc
          - name: home
            emptyDir:
              sizeLimit: 4Gi
        nodeSelector:
          Application: automation
          Archtype: x86
          kubernetes.io/arch: amd64
        tolerations:
          - key: dedicated.falco.org/automation
            operator: Equal
            value: "true"
            effect: NoSchedule
