postsubmits:
  falcosecurity/falco-website:
  - name: peribolos-syncer-falco-website-post
    branches:
    - ^master$
    decorate: true
    max_concurrency: 1
    skip_report: false
    run_if_changed: 'OWNERS$'
    spec:
      containers:
      - image: ghcr.io/falcosecurity/peribolos-syncer:0.2.2
        command:
        - peribolos-syncer
        args:
        - sync
        - github
        - --org=falcosecurity
        - --team=falco-website-maintainers
        - --peribolos-config-path=config/org.yaml
        - --peribolos-config-repository=test-infra
        - --peribolos-config-git-ref=master
        - --owners-repository=falco-website
        - --owners-git-ref=master
        - --approvers-only=true
        - --git-author-name=poiana
        - --git-author-email="51138685+poiana@users.noreply.github.com"
        - --gpg-public-key=/tmp/gpg-pub/poiana.pub
        - --gpg-private-key=/tmp/gpg/poiana.asc
        - --github-username=poiana
        - --github-endpoint=http://ghproxy.default.svc.cluster.local
        - --github-endpoint=https://api.github.com
        - --github-hourly-tokens=1200
        - --github-token-path=/etc/github-token/oauth
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
          readOnly: true
        - name: gpg-signing-key
          mountPath: /tmp/gpg
          readOnly: true
        - name: gpg-signing-key-pub
          mountPath: /tmp/gpg-pub
          readOnly: true
      volumes:
      - name: github
        secret:
          secretName: oauth-token
      - name: gpg-signing-key
        secret:
          secretName: poiana-gpg-signing-key
          defaultMode: 0400
      - name: gpg-signing-key-pub
        secret:
          secretName: poiana-gpg-signing-key-pub
          defaultMode: 0400
      nodeSelector:
        Archtype: "x86"

