apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../jobs/oci
  - namespaces.yaml
  - driverkit.yaml
  - automation.yaml
  - driverkit-policy.yaml
  - log-storage-policy.yaml
  - prowjob-crd.yaml
  - ghproxy.yaml
  - hook.yaml
  - horologium.yaml
  - prow-controller-manager.yaml
  - sinker.yaml
  - crier.yaml
  - deck.yaml
  - monitoring.yaml
  - tide.yaml
  - needs-rebase.yaml
  - status-reconciler.yaml
patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: Prune=confirm,Delete=confirm
configMapGenerator:
  - name: branding
    namespace: prow
    files:
      - branding/favicon.png
      - branding/logo.png
      - branding/style.css
    options:
      labels:
        app.kubernetes.io/name: deck
        app.kubernetes.io/component: dashboard
        app.kubernetes.io/part-of: prow
  - name: config
    namespace: prow
    files:
      - config.yaml
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/part-of: prow
  - name: plugins
    namespace: prow
    files:
      - plugins.yaml
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/part-of: prow
