apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins
  namespace: prow
  labels:
    app.kubernetes.io/name: hook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: prow
data:
  plugins.yaml: |
    triggers:
      - repos:
          - falcosecurity
        join_org_url: "https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md"
        only_org_members: true
    plugins:
      falcosecurity/test-infra:
        plugins:
          - trigger
