periodics:
  - name: periodic-close
    interval: 6h
    decorate: true
    annotations:
      description: Closes rotten issues after 30d of inactivity
    agent: kubernetes
    spec:
      containers:
        - image: gcr.io/k8s-prow/commenter:v20230315-6d54c174f4
          command:
            - commenter
          args:
            - |-
              --query=org:falcosecurity
              -label:lifecycle/frozen
              label:lifecycle/rotten
            - --updated=720h
            - --token=/etc/github/oauth
            - --endpoint=http://ghproxy.default.svc.cluster.local
            - |-
              --comment=Rotten issues close after 30d of inactivity.

              Reopen the issue with `/reopen`.

              Mark the issue as fresh with `/remove-lifecycle rotten`.

              Provide feedback via https://github.com/falcosecurity/community.
              /close
            - --template
            - --confirm
            - --ceiling=10
          volumeMounts:
          - name: oauth
            mountPath: /etc/github
            readOnly: true
      volumes:
      - name: oauth
        secret:
          secretName: oauth-token
      nodeSelector:
        Archtype: "x86"
