periodics:
  - name: update-drivers-website
    cron: '0 0 * * *'  # every midnight, daily
    decorate: true
    extra_refs:
    # Check out the falcosecurity/test-infra repo
    # This will be the working directory
    - org: falcosecurity
      repo: test-infra
      base_ref: master
      workdir: true
    spec:
      containers:
      # See images/update-drivers-site
      - image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/update-drivers-website
        imagePullPolicy: Always
        command:
        - /entrypoint.sh
        env:
        - name: AWS_REGION
          value: eu-west-1
      nodeSelector:
        Archtype: "x86"
