periodics:
  - name: update-drivers-website
    cron: '0 12 * * *'  # every day at 12pm
    decorate: true
    spec:
      serviceAccountName: driver-kit
      containers:
      # See images/update-drivers-site
      - image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/update-drivers-website
        imagePullPolicy: Always
        command:
        - /entrypoint.sh
        env:
        - name: AWS_REGION
          value: eu-west-1
      nodeSelector:
        Archtype: "x86"
