{
 "title": "hook dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "webhook counter",
   "type": "singlestat",
   "description": "sum(prow_webhook_counter)",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(prow_webhook_counter)" }
   ]
  },
  {
   "title": "webhook response codes",
   "type": "singlestat",
   "description": "sum(prow_webhook_response_codes)",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prow_webhook_response_codes)"
    }
   ]
  },
  {
   "title": "incoming webhooks by event type",
   "type": "graph",
   "description": "sum(rate(prow_webhook_counter[1m])) by (event_type)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prow_webhook_counter[1m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "webhook response codes",
   "type": "graph",
   "description": "sum(rate(prow_webhook_response_codes[1m])) by (response_code)",
   "gridPos": { "h": 9, "w": 24, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prow_webhook_response_codes[1m])) by (response_code)",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "configmap capacities",
   "type": "graph",
   "description": "prow_configmap_size_bytes / 1048576",
   "gridPos": { "h": 9, "w": 24, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "prow_configmap_size_bytes / 1048576",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  }
 ]
}