deck:
  branding:
    header_color: "#00AEC7" # Falco Teal
    logo: "/static/extensions/favicon.png"
    favicon: "/static/extensions/favicon.png"
  spyglass:
    size_limit: 500000000 # 500MB
    lenses:
      - lens:
          name: metadata
        required_files:
        - started.json|finished.json
        optional_files:
        - podinfo.json
      - lens:
          name: buildlog
        required_files:
          - build-log.txt
      - lens:
          name: podinfo
        required_files:
          - podinfo.json

plank:
  job_url_template: 'http://prow.falco.org/view/s3/falco-prow-logs/{{if eq .Spec.Type "presubmit"}}pr-logs/pull{{else if eq .Spec.Type "batch"}}pr-logs/pull{{else}}logs{{end}}{{if .Spec.Refs}}{{if ne .Spec.Refs.Org ""}}/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}{{end}}{{end}}{{if eq .Spec.Type "presubmit"}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/batch{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/'
  job_url_prefix_config:
    '*': http://prow.falco.org/view/
  report_templates:
    '*': '[Full PR test history](http://prow.falco.org/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/{{.Spec.Refs.Org}}/{{.Spec.Refs.Repo}}/issues?q=is:issue+is:open) when you hit one in your PR.'
  allow_cancellations: true # AllowCancellations enables aborting presubmit jobs for commits that have been superseded by newer commits in Github pull requests.
  max_concurrency: 100 # Limit of concurrent ProwJobs. Need to be adjusted depending of the cluster size.
  pod_pending_timeout: 60m
  default_decoration_configs:
    '*':
      timeout: 12h # Up to 12 hours for driverkit builder jobs
      grace_period: 10m
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20201124-061f85d859"
        initupload: "gcr.io/k8s-prow/initupload:v20201124-061f85d859"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20201124-061f85d859"
        sidecar: "gcr.io/k8s-prow/sidecar:v20201124-061f85d859"
      gcs_configuration:
        bucket: s3://falco-prow-logs
        path_strategy: explicit
      s3_credentials_secret: "s3-credentials" #secret in use with IAM creds for sidecar pod log upload

sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 24h
  terminated_pod_ttl: 2h

branch-protection:
  enforce_admins: true # rules apply to admins too!
  restrictions: # restrict who can push
    teams: ["maintainers", "machine_users"]
  required_pull_request_reviews:
    dismiss_stale_reviews: true # automat dismiss old reviews
    dismissal_restrictions: # allow review dismissals
      teams:
        - maintainers
        - machine_users
    require_code_owner_reviews: true # require a code owner approval
    required_approving_review_count: 1 # number of approvals
  required_status_checks:
    strict: false # we don't want to block any PR if it's not up to date, we have the rebase merge strategy and needs-rebase plugin
  orgs:
    falcosecurity:
      # dco check is required for all PRs of any falcosecurity project
      required_status_checks:
        contexts:
          - dco
      repos:
        .github:
          branches:
            master:
              protect: true
        advocacy:
          branches:
            master:
              protect: true
        charts:
          branches:
            master:
              protect: true
            gh-pages:
              protect: true
              enforce_admins: false # do not enforce all configured restrictions for admins, since our bot needs to push while the CI workflow is running
              required_pull_request_reviews: # disable PR reviews since our bot needs to push while the CI workflow is running
                require_code_owner_reviews: false
                required_approving_review_count: 0
        client-go:
          branches:
            master:
              protect: true
          required_status_checks:
            contexts:
              - "ci/circleci: test"
        client-py:
          branches:
            master:
              protect: true
        client-rs:
          branches:
            master:
              protect: true
        cloud-native-security-hub:
          branches:
            master:
              protect: true
        cloud-native-security-hub-frontend:
          branches:
            master:
              protect: true
        cloud-native-security-hub-backend:
          branches:
            master:
              protect: true
        community:
          branches:
            master:
              protect: true
        driverkit:
          branches:
            master:
              protect: true
        evolution:
          branches:
            master:
              protect: true
        event-generator:
          branches:
            master:
              protect: true
        falco:
          required_pull_request_reviews:
            required_approving_review_count: 2
          required_status_checks:
            contexts:
              - "ci/circleci: integration"
              - "ci/circleci: centos7"
              - "ci/circleci: musl"
          branches:
            master:
              protect: true
            "release/0.26.2":
              protect: true
        falcosidekick:
          branches:
            master:
              protect: true
        falco-exporter:
          branches:
            master:
              protect: true
          required_status_checks:
            contexts:
              - "ci/circleci: test"
        falcoctl:
          branches:
            master:
              protect: true
        falco-website:
          branches:
            master:
              protect: true
          required_status_checks:
            contexts:
              - "netlify/falcosecurity/deploy-preview"
        kilt:
          branches:
            master:
              protect: true
        pdig:
          branches:
            master:
              protect: true
        template-repository:
          branches:
            master:
              protect: true
        test-infra:
          branches:
            master:
              protect: true
          required_status_checks:
            contexts:
              - "ci/circleci: build/amazonlinux"
              - "ci/circleci: build/amazonlinux2"
              - "ci/circleci: build/centos"
              - "ci/circleci: build/debian"
              - "ci/circleci: build/ubuntu-aws"
              - "ci/circleci: build/ubuntu-generic"

log_level: debug

pod_namespace: test-pods

prowjob_namespace: default

tide:
  context_options:
    skip-unknown-contexts: true
    from-branch-protection: true
  merge_method:
    falcosecurity/.github: rebase
    falcosecurity/advocacy: rebase
    falcosecurity/charts: rebase
    falcosecurity/client-go: rebase
    falcosecurity/client-py: rebase
    falcosecurity/client-rs: rebase
    falcosecurity/cloud-native-security-hub: rebase
    falcosecurity/cloud-native-security-hub-frontend: rebase
    falcosecurity/cloud-native-security-hub-backend: rebase
    falcosecurity/community: rebase
    falcosecurity/driverkit: rebase
    falcosecurity/evolution: rebase
    falcosecurity/event-generator: rebase
    falcosecurity/falco: rebase
    falcosecurity/falcosidekick: rebase
    falcosecurity/falco-exporter: rebase
    falcosecurity/falcoctl: rebase
    falcosecurity/falco-website: rebase
    falcosecurity/kilt: rebase
    falcosecurity/pdig: rebase
    falcosecurity/template-repository: rebase
    falcosecurity/test-infra: rebase
  queries:
    - repos:
        - falcosecurity/.github
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/advocacy
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/charts
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/client-go
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/event-generator
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/falco
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/client-py
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/client-rs
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/cloud-native-security-hub
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/cloud-native-security-hub-frontend
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/cloud-native-security-hub-backend
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/community
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/driverkit
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/evolution
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/falco
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/falcosidekick
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/falcoctl
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/falco
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/falco-exporter
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/falco-website
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/kilt
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/pdig
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/test-infra
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/template-repository
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
