orgs:
  falcosecurity:
    actions:
      secrets:
        - DOCKERHUB_SECRET
        - DOCKERHUB_USER
    repos:
      falco:
        actions:
          secrets:
            - GPG_KEY
      libs:
        actions:
          secrets:
            - FEDEDP_GIST_SECRET
            - PPC64LE_HOST
            - PPC64LE_KEY
            - PPC64LE_PORT
            - PPC64LE_USERNAME
  
