presubmits:
  falcosecurity/plugins:
  - name: build-plugins-presubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    always_run: true  # Run for every PR, but master
    path_alias: github.com/falcosecurity/plugins
    spec:
      containers:
      - command:
        - /build.sh
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-plugins:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 3Gi
      nodeSelector:
        Archtype: "x86"
postsubmits:
  falcosecurity/plugins:
  - name: build-plugins-postsubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    spec:
      serviceAccountName: build-plugins
      containers:
      - command:
        - /build-and-publish.sh
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-plugins:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 3Gi
      nodeSelector:
        Archtype: "x86"
  - name: build-plugins-release-postsubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^[a-z]+[a-z0-9_]*-(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?$
    spec:
      serviceAccountName: build-plugins
      containers:
      - command:
        - /build-and-publish.sh
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-plugins:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 3Gi
      nodeSelector:
        Archtype: "x86"
  - name: build-plugins-update-readme-postsubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: "^registry.yaml"
    spec:
      serviceAccountName: build-plugins
      containers:
      - command:
        - /update-readme.sh
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-plugins:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 1Gi
      nodeSelector:
        Archtype: "x86"
