presubmits:
  falcosecurity/plugins:
  - name: build-plugins
    decorate: true
    skip_report: false
    agent: kubernetes
    always_run: true  # Run for every PR, but master
    spec:
      containers:
      - command:
        - /workspace/build.sh
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/golang:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
      nodeSelector:
        Archtype: "x86"
