presubmits:
  falcosecurity/plugins:
  - name: build-plugins
    decorate: true
    skip_report: false
    agent: kubernetes
    always_run: true  # Run for every PR, but master
    path_alias: github.com/falcosecurity/plugins
    spec:
      containers:
      - command:
        - /home/prow/go/src/github.com/falcosecurity/plugins/build.sh
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: golang:1.15
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
      nodeSelector:
        Archtype: "x86"
