periodics:
  - name: update-falco-k8s-manifests
    cron: "0 10 * * *" # Run everyday at 10:00
    decorate: true
    extra_refs:
    # Check out the falcosecurity/deploy-kubernetes repo
    # This will be the working directory
    - org: falcosecurity
      repo: deploy-kubernetes
      base_ref: main
      workdir: true
    spec:
      containers:
      # See images/update-falco-k8s-manifests
      - image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/update-falco-k8s-manifests
        imagePullPolicy: Always
        command:
        - /entrypoint.sh
        args:
        - /etc/github-token/oauth
        env:
        - name: GH_PROXY
          value: https://api.github.com # fixme > Can't reach http://ghproxy at the moment
        - name: HELM_CHART_NAME
          value: falco
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
          readOnly: true
        - name: gpg-signing-key
          mountPath: /root/gpg-signing-key/
          readOnly: true
      volumes:
      - name: github
        secret:
          # Secret containing a GitHub user access token with `repo` scope for creating PRs.
          secretName: oauth-token
      - name: gpg-signing-key
        secret:
          secretName: poiana-gpg-signing-key
          defaultMode: 0400
      nodeSelector:
        Archtype: "x86"
  - name: update-falco-exporter-k8s-manifests
    cron: "0 11 * * *" # Run everyday at 11:00
    decorate: true
    extra_refs:
    # Check out the falcosecurity/deploy-kubernetes repo
    # This will be the working directory
    - org: falcosecurity
      repo: deploy-kubernetes
      base_ref: main
      workdir: true
    spec:
      containers:
      # See images/update-falco-k8s-manifests
      - image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/update-falco-k8s-manifests
        imagePullPolicy: Always
        command:
        - /entrypoint.sh
        args:
        - /etc/github-token/oauth
        env:
        - name: GH_PROXY
          value: https://api.github.com # fixme > Can't reach http://ghproxy at the moment
        - name: HELM_CHART_NAME
          value: falco-exporter
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
          readOnly: true
        - name: gpg-signing-key
          mountPath: /root/gpg-signing-key/
          readOnly: true
      volumes:
      - name: github
        secret:
          # Secret containing a GitHub user access token with `repo` scope for creating PRs.
          secretName: oauth-token
      - name: gpg-signing-key
        secret:
          secretName: poiana-gpg-signing-key
          defaultMode: 0400
      nodeSelector:
        Archtype: "x86"
  - name: update-falco-sidekick-k8s-manifests
    cron: "0 12 * * *" # Run everyday at 12:00
    decorate: true
    extra_refs:
    # Check out the falcosecurity/deploy-kubernetes repo
    # This will be the working directory
    - org: falcosecurity
      repo: deploy-kubernetes
      base_ref: main
      workdir: true
    spec:
      containers:
      # See images/update-falco-k8s-manifests
      - image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/update-falco-k8s-manifests
        imagePullPolicy: Always
        command:
        - /entrypoint.sh
        args:
        - /etc/github-token/oauth
        env:
        - name: GH_PROXY
          value: https://api.github.com # fixme > Can't reach http://ghproxy at the moment
        - name: HELM_CHART_NAME
          value: falcosidekick
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
          readOnly: true
        - name: gpg-signing-key
          mountPath: /root/gpg-signing-key/
          readOnly: true
      volumes:
      - name: github
        secret:
          # Secret containing a GitHub user access token with `repo` scope for creating PRs.
          secretName: oauth-token
      - name: gpg-signing-key
        secret:
          secretName: poiana-gpg-signing-key
          defaultMode: 0400
      nodeSelector:
        Archtype: "x86"
  - name: update-event-generator-k8s-manifests
    cron: "0 13 * * *" # Run everyday at 13:00
    decorate: true
    extra_refs:
    # Check out the falcosecurity/deploy-kubernetes repo
    # This will be the working directory
    - org: falcosecurity
      repo: deploy-kubernetes
      base_ref: main
      workdir: true
    spec:
      containers:
      # See images/update-falco-k8s-manifests
      - image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/update-falco-k8s-manifests
        imagePullPolicy: Always
        command:
        - /entrypoint.sh
        args:
        - /etc/github-token/oauth
        env:
        - name: GH_PROXY
          value: https://api.github.com # fixme > Can't reach http://ghproxy at the moment
        - name: HELM_CHART_NAME
          value: event-generator
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
          readOnly: true
        - name: gpg-signing-key
          mountPath: /root/gpg-signing-key/
          readOnly: true
      volumes:
      - name: github
        secret:
          # Secret containing a GitHub user access token with `repo` scope for creating PRs.
          secretName: oauth-token
      - name: gpg-signing-key
        secret:
          secretName: poiana-gpg-signing-key
          defaultMode: 0400
      nodeSelector:
        Archtype: "x86"
