postsubmits:
  falcosecurity/test-infra:
    - name: update-secrets-post-submit
      branches:
        - ^master$
      decorate: true
      max_concurrency: 1
      run_if_changed: '^config/secrets.yaml$'
      spec:
        containers:
          - image: ghcr.io/falcosecurity/pigeon:v0.3.0
            command:
              - pigeon
            args:
              - --conf=config/secrets.yaml
              - --gh-token=/etc/github/oauth
              - --verbose
            volumeMounts:
              - name: github
                mountPath: /etc/github
                readOnly: true
        volumes:
          - name: github
            secret:
              secretName: oauth-token
        nodeSelector:
          Archtype: "x86"
