presubmits:
  falcosecurity/test-infra:
  - name: validate-new-drivers-debian-presubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/(.+/)?debian_.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - debian
        env:
        - name: DBG_MAKE_BUILD_TARGET
          value: validate
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "x86"
        Application: "jobs"
postsubmits:
  falcosecurity/test-infra:
  - name: build-new-drivers-debian-postsubmit
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/x86_64/debian_.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - debian
        env:
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "x86"
        Application: "jobs"
  - name: build-new-drivers-debian-postsubmit-arm
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/aarch64/debian_.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - debian
        env:
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Archtype"
        operator: "Equal"
        value: "arm"
        effect: "NoSchedule"
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "arm"
        Application: "jobs"
