postsubmits:
  falcosecurity/test-infra:
  - name: build-new-drivers-ubuntu-azure-3-postsubmit
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/x86_64/ubuntu-azure_3.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-azure
        - "3.*"
        env:
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Application: "jobs"
        Archtype: "x86"
  - name: build-new-drivers-ubuntu-azure-3-postsubmit-arm
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/aarch64/ubuntu-azure_3.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-azure
        - "3.*"
        env:
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Archtype"
        operator: "Equal"
        value: "arm"
        effect: "NoSchedule"
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Application: "jobs"
        Archtype: "arm"
  - name: build-new-drivers-ubuntu-azure-4-postsubmit
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/x86_64/ubuntu-azure_4.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-azure
        - "4.*"
        env:
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Application: "jobs"
        Archtype: "x86"
  - name: build-new-drivers-ubuntu-azure-4-postsubmit-arm
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/aarch64/ubuntu-azure_4.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-azure
        - "4.*"
        env:
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Archtype"
        operator: "Equal"
        value: "arm"
        effect: "NoSchedule"
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Application: "jobs"
        Archtype: "arm"
  - name: build-new-drivers-ubuntu-azure-5-postsubmit
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/x86_64/ubuntu-azure_5.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-azure
        - "5.*"
        env:
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Application: "jobs"
        Archtype: "x86"
  - name: build-new-drivers-ubuntu-azure-5-postsubmit-arm
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/aarch64/ubuntu-azure_5.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-azure
        - "5.*"
        env:
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Archtype"
        operator: "Equal"
        value: "arm"
        effect: "NoSchedule"
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Application: "jobs"
        Archtype: "arm"
  - name: build-new-drivers-ubuntu-azure-6-postsubmit
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/x86_64/ubuntu-azure_6.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-azure
        - "6.*"
        env:
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Application: "jobs"
        Archtype: "x86"
  - name: build-new-drivers-ubuntu-azure-6-postsubmit-arm
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/aarch64/ubuntu-azure_6.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-azure
        - "6.*"
        env:
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Archtype"
        operator: "Equal"
        value: "arm"
        effect: "NoSchedule"
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Application: "jobs"
        Archtype: "arm"
