presubmits:
  falcosecurity/test-infra:
  - name: rebuild-all-drivers-debian
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    always_run: false
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - debian
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        - name: SKIP_EXISTING
          value: "false"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 6Gi
      nodeSelector:
        Archtype: "x86"
periodics:
  - name: rebuild-all-drivers-debian-periodic
    decorate: true
    cron: "0 03 * * 4"
    extra_refs:
    - org: falcosecurity
      repo: test-infra
      base_ref: master
    agent: kubernetes
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - debian
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        - name: SKIP_EXISTING
          value: "false"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 6Gi
      nodeSelector:
        Archtype: "x86"
