presubmits:
  falcosecurity/libs:
  - name: build-libs
    decorate: true
    skip_report: false
    agent: kubernetes
    always_run: true  # Run for every PR, but master
    spec:
      containers:
      - command:
        - /build.sh
        args:
        - -DBUILD_BPF=On
        - -DUSE_BUNDLED_DEPS=False
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-libs:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
      nodeSelector:
        Archtype: "x86"
  - name: build-libs-arm
    decorate: true
    skip_report: false
    agent: kubernetes
    always_run: true  # Run for every PR, but master
    spec:
      containers:
      - command:
        - /build.sh
        args:
        - -DBUILD_BPF=On
        - -DUSE_BUNDLED_DEPS=False
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-libs:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
      nodeSelector:
        Archtype: "arm"
      tolerations:
      - key: "Archtype"
        operator: "Equal"
        value: "arm"
        effect: "NoSchedule"
  - name: build-libs-bundled-deps
    decorate: true
    skip_report: false
    agent: kubernetes
    always_run: true  # Run for every PR, but master
    spec:
      containers:
      - command:
        - /build.sh
        args:
        - -DBUILD_BPF=On
        - -DUSE_BUNDLED_DEPS=True
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-libs:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
      nodeSelector:
        Archtype: "x86"
  - name: build-libs-with-chisels
    decorate: true
    skip_report: false
    agent: kubernetes
    always_run: true  # Run for every PR, but master
    spec:
      containers:
      - command:
        - /build.sh
        args:
        - -DBUILD_BPF=On
        - -DWITH_CHISEL=True
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-libs:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
      nodeSelector:
        Archtype: "x86"
  - name: build-libs-minimal
    decorate: true
    skip_report: false
    agent: kubernetes
    always_run: true  # Run for every PR, but master
    spec:
      containers:
      - command:
        - /build.sh
        args:
        - -DMINIMAL_BUILD=True
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-libs:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
      nodeSelector:
        Archtype: "x86"
