apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/falcosecurity/test-infra.git
    targetRevision: HEAD
    path: config/applications/oci/falco
    directory:
      recurse: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: falco
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
