apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oci-public-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/falcosecurity/test-infra.git
    targetRevision: HEAD
    path: config/applications/oci/gateway
    directory:
      recurse: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
