apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/falcosecurity/test-infra.git
    targetRevision: master
    path: config/prow/oci
  destination:
    server: https://kubernetes.default.svc
    namespace: prow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - FailOnSharedResource=true
      - PruneLast=true
