# PROW_INSTANCE_SPECIFIC
# Very customized metrics endpoints
apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: prow-monitoring
type: Opaque
stringData:
  prometheus-additional.yaml: |
    - job_name: k8s-prow-builds-new-boskos
      metrics_path: /metrics
      static_configs:
        - targets:
            - "104.197.27.114:9090"  # external ip boskos-metrics in k8s-prow-builds cluster
    - job_name: k8s-infra-prow-builds-boskos
      metrics_path: /metrics
      static_configs:
        - targets:
            - "35.225.208.117:9090"  # external ip boskos-metrics in k8s-infra-prow-build cluster
    - job_name: greenhouse-metrics
      metrics_path: /prometheus
      static_configs:
        - targets:
            - "35.225.115.154" # external ip greenhouse-metrics for k8s-prow-builds
    - job_name: blackbox
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          # ATTENTION: Keep this in sync with the list in mixins/prometheus/prober_alerts.libsonnet
          - https://prow.falco.org
          - https://monitoring.prow.falco.org
          - https://testgrid.falco.org
          - https://gubernator.falco.org
          - https://gubernator.falco.org/pr/fejta # Deep health check of someone's PR dashboard.
          - https://storage.googleapis.com/k8s-gubernator/triage/index.html
          - https://storage.googleapis.com/test-infra-oncall/oncall.html
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-prober

