presubmits:
  falcosecurity/plugin-sdk-go:
  - name: build-plugin-sdk-go
    decorate: true
    skip_report: false
    agent: kubernetes
    always_run: true  # Run for every PR, but master
    spec:
      containers:
      - command:
        - /code/github.com/falcosecurity/plugins/build.sh
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: golang:1.15
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
      nodeSelector:
        Archtype: "x86"
