presubmits:
  falcosecurity/test-infra:
    - name: arm-test
      branches:
        - ^feat/arm-testing
      decorate: true
      skip_report: false
      always_run: true
      spec:
        containers:
        - image: arm32v7/bash
          command:
          - echo
          args:
          - "hello"
        nodeSelector:
          Archtype: "arm"
        tolerations:
        - key: "Archtype"
          operator: "Equal"
          value: "arm"
          effect: "NoSchedule"
periodics:
- name: arm-test
  interval: 30m
  extra_refs:
  # Check out the repo containing the maintainers file
  # This will be the working directory
  - org: falcosecurity
    repo: falco
    base_ref: master
    workdir: true
  spec:
    containers:
    - image: multiarch/alpine:aarch64-v3.12
      command:
      - sleep
      # - "/build.sh"
      args:
      - "1800"
      # - "falco"
    nodeSelector:
      Archtype: "arm"
    tolerations:
    - key: "Archtype"
      operator: "Equal"
      value: "arm"
      effect: "NoSchedule"
