periodics:
- name: arm-build-falco
  decorate: true
  decoration_config:
    utility_images:
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20220414-949f7bddd3-arm64"
      initupload: "gcr.io/k8s-prow/initupload:v20220414-949f7bddd3-arm64"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20220414-949f7bddd3-arm64"
      sidecar: "gcr.io/k8s-prow/sidecar:v20220414-949f7bddd3-arm64"
  cron: "0 15 * * 1"
  spec:
    containers:
    - image: multiarch/alpine:aarch64-v3.12
      command:     
      - bin/sh
      - -c
      - >
        apk update
        &&
        apk add g++ gcc cmake cmake make ncurses-dev git bash perl linux-headers autoconf automake m4 libtool elfutils-dev libelf-static patch binutils
        &&
        git clone https://github.com/falcosecurity/falco.git
        &&
        cmake -DUSE_BUNDLED_DEPS=On -DMUSL_OPTIMIZED_BUILD=On -DBUILD_DRIVER=Off /falco
        &&
        make -j4 falco
    nodeSelector:
      Archtype: "arm"
    tolerations:
    - key: "Archtype"
      operator: "Equal"
      value: "arm"
      effect: "NoSchedule"
- name: arm-build-falco-grpc
  decorate: true
  cron: "0 15 * * 2"
  # interval: 1h
  spec:
    containers:
    - image: multiarch/alpine:aarch64-v3.12
      command:     
      - bin/sh
      - -c
      - >
        apk update
        &&
        apk add g++ gcc cmake cmake make ncurses-dev git bash perl linux-headers autoconf automake m4 libtool elfutils-dev libelf-static patch binutils
        &&
        git clone https://github.com/falcosecurity/falco.git
        &&
        cmake -DUSE_BUNDLED_DEPS=On -DMUSL_OPTIMIZED_BUILD=On -DBUILD_DRIVER=Off /falco
        &&
        make -j4 grpc
    nodeSelector:
      Archtype: "arm"
    tolerations:
    - key: "Archtype"
      operator: "Equal"
      value: "arm"
      effect: "NoSchedule"
