periodics:
- name: arm-test-falco
  cron: "0 15 * * 1"
  spec:
    containers:
    - image: multiarch/alpine:aarch64-v3.12
      command:     
      - bin/sh
      - -c
      - >
        apk update
        &&
        apk add g++ gcc cmake cmake make ncurses-dev git bash perl linux-headers autoconf automake m4 libtool elfutils-dev libelf-static patch binutils
        &&
        git clone https://github.com/falcosecurity/falco.git
        &&
        cmake -DUSE_BUNDLED_DEPS=On -DMUSL_OPTIMIZED_BUILD=On -DBUILD_DRIVER=Off /falco
        &&
        make -j4 falco
    nodeSelector:
      Archtype: "arm"
    tolerations:
    - key: "Archtype"
      operator: "Equal"
      value: "arm"
      effect: "NoSchedule"
- name: arm-test-falco-grpc
  cron: "0 15 * * 2"
  spec:
    containers:
    - image: multiarch/alpine:aarch64-v3.12
      command:     
      - bin/sh
      - -c
      - >
        apk update
        &&
        apk add g++ gcc cmake cmake make ncurses-dev git bash perl linux-headers autoconf automake m4 libtool elfutils-dev libelf-static patch binutils
        &&
        git clone https://github.com/falcosecurity/falco.git
        &&
        cmake -DUSE_BUNDLED_DEPS=On -DMUSL_OPTIMIZED_BUILD=On -DBUILD_DRIVER=Off /falco
        &&
        make -j4 grpc
    nodeSelector:
      Archtype: "arm"
    tolerations:
    - key: "Archtype"
      operator: "Equal"
      value: "arm"
      effect: "NoSchedule"
- name: arm-test-falco-package
  cron: "0 15 * * 3"
  spec:
    containers:
    - image: multiarch/alpine:aarch64-v3.12
      command:     
      - bin/sh
      - -c
      - >
        apk update
        &&
        apk add g++ gcc cmake cmake make ncurses-dev git bash perl linux-headers autoconf automake m4 libtool elfutils-dev libelf-static patch binutils
        &&
        git clone https://github.com/falcosecurity/falco.git
        &&
        cmake -DUSE_BUNDLED_DEPS=On -DMUSL_OPTIMIZED_BUILD=On -DBUILD_DRIVER=Off /falco
        &&
        make -j4 package
    nodeSelector:
      Archtype: "arm"
    tolerations:
    - key: "Archtype"
      operator: "Equal"
      value: "arm"
      effect: "NoSchedule"
- name: arm-test-falco-tests
  cron: "0 15 * * 4"
  spec:
    containers:
    - image: multiarch/alpine:aarch64-v3.12
      command:     
      - bin/sh
      - -c
      - >
        apk update
        &&
        apk add g++ gcc cmake cmake make ncurses-dev git bash perl linux-headers autoconf automake m4 libtool elfutils-dev libelf-static patch binutils
        &&
        git clone https://github.com/falcosecurity/falco.git
        &&
        cmake -DUSE_BUNDLED_DEPS=On -DMUSL_OPTIMIZED_BUILD=On -DBUILD_DRIVER=Off /falco
        &&
        make -j4 tests
    nodeSelector:
      Archtype: "arm"
    tolerations:
    - key: "Archtype"
      operator: "Equal"
      value: "arm"
      effect: "NoSchedule"
