name: Terraform apply

on:
  push:
    branches:
    - master
    paths:
    - 'config/clusters/aws/**'
    - '.github/workflows/terraform-apply.yml'
    - 'tools/ci/apply-terraform-aws.sh'

concurrency:
  group: master-CI
  cancel-in-progress: false

defaults:
  run:
    working-directory: config/clusters/aws

jobs:
  plan:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      with:
        terraform_version: '1.15.6'
        terraform_wrapper: false

    - name: Configure AWS credentials 🔧⚙️
      uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
      with:
        role-to-assume: "arn:aws:iam::292999226676:role/github_actions-test-infra-cluster"
        aws-region: eu-west-1

    - name: Validate, plan and apply AWS Terraform
      id: apply
      run: bash "$GITHUB_WORKSPACE/tools/ci/apply-terraform-aws.sh"
