name: Update DBG image

on:
  pull_request:
    paths:
      - images/update-dbg/**
      - .github/workflows/update-dbg-image.yml
  push:
    branches: [master]
    paths:
      - images/update-dbg/**
      - .github/workflows/update-dbg-image.yml
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: update-dbg-image-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: build-update-dbg-image
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          context: images/update-dbg
          platforms: linux/amd64
          push: false

  publish:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          context: images/update-dbg
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/falcosecurity/test-infra/update-dbg:0.18.0-1
            ghcr.io/falcosecurity/test-infra/update-dbg:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/falcosecurity/test-infra
            org.opencontainers.image.revision=${{ github.sha }}
